# Generated by Django 2.1.3 on 2018-11-18 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Coevaluation',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CoevaluationSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('answers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Answer')),
                ('coevaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Coevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRecordForStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('coevaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Coevaluation')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRecordForStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Course')),
            ],
        ),
        migrations.AddField(
            model_name='teamrecordforstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='teamrecordforstudent',
            name='work_teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.WorkTeam'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.WorkTeam'),
        ),
        migrations.AddField(
            model_name='courserecordforstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='aides',
            field=models.ManyToManyField(related_name='courses_as_aide', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='auxiliaries',
            field=models.ManyToManyField(related_name='courses_as_auxiliary', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, to='coevaluador.Question'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_as_student', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses_as_teacher', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='coevaluationsheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='coevaluationsheet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.WorkTeam'),
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Course'),
        ),
        migrations.AddField(
            model_name='coevaluation',
            name='question',
            field=models.ManyToManyField(to='coevaluador.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='coevaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Coevaluation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='coevaluador.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coevaluador.Question'),
        ),
    ]
