# Generated by Django 2.1.3 on 2018-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='courses_as_questions', to='coevaluador.Question'),
        ),
    ]
