# Generated by Django 2.1.3 on 2018-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rango', 'Rango'), ('textbox', 'Cuadro de Texto'), ('dropdown', 'Opciones desplegables')], default='rango', max_length=100),
        ),
        migrations.AlterField(
            model_name='coevaluation',
            name='question',
            field=models.ManyToManyField(blank=True, to='coevaluador.Question'),
        ),
    ]
