# Generated by Django 2.1.3 on 2018-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0002_auto_20181120_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rango', 'Rango'), ('textbox', 'Cuadro de Texto')], default='rango', max_length=100),
        ),
    ]
