# Generated by Django 2.1.3 on 2018-11-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0003_auto_20181120_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluation',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=50),
        ),
    ]
