# Generated by Django 2.1.3 on 2018-11-21 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0004_auto_20181120_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coevaluationsheet',
            name='student',
        ),
        migrations.AddField(
            model_name='coevaluationsheet',
            name='coevaluated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coevaluated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coevaluationsheet',
            name='coevaluator',
            field=models.ForeignKey(default=195228191, on_delete=django.db.models.deletion.CASCADE, related_name='coevaluator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coevaluationsheet',
            name='status',
            field=models.CharField(choices=[('answered', 'Contestada'), ('not_answered', 'No Contestada')], default='not_answered', max_length=100),
        ),
    ]
