# Generated by Django 2.1.3 on 2018-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0005_auto_20181121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluationsheet',
            name='status',
            field=models.CharField(choices=[('answered', 'Contestada'), ('not_answered', 'No Contestada')], default='No Contestada', max_length=100),
        ),
    ]
