# Generated by Django 2.1.3 on 2018-11-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0007_auto_20181121_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='ans',
        ),
    ]
