# Generated by Django 2.1.3 on 2018-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0008_auto_20181121_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluationsheet',
            name='status',
            field=models.CharField(choices=[('answered', 'Contestada'), ('not_answered', 'No Contestada')], default='not_answered', max_length=100),
        ),
    ]
