# Generated by Django 2.1.3 on 2018-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0010_auto_20181121_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='coevaluationsheet',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
