# Generated by Django 2.1.3 on 2018-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0011_coevaluationsheet_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluation',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Publicada', 'Publicada')], default='Abierta', max_length=50),
        ),
        migrations.AlterField(
            model_name='coevaluationsheet',
            name='status',
            field=models.CharField(choices=[('answered', 'Contestada'), ('not_answered', 'No Pendiente')], default='not_answered', max_length=100),
        ),
    ]
