# Generated by Django 2.1.3 on 2018-11-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0013_auto_20181121_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'code', 'section', 'year', 'semester')},
        ),
    ]
