# Generated by Django 2.1.3 on 2018-11-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coevaluador', '0014_auto_20181121_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluation',
            name='status',
            field=models.CharField(choices=[('opened', 'Abierta'), ('closed', 'Cerrada'), ('published', 'Publicada')], default='opened', max_length=50),
        ),
    ]
